# x64lens development container
#
# Purpose:
#   Provide a reproducible Ubuntu-based build and test environment for the
#   NASM-first x64lens toolchain. This container is meant for development,
#   CI smoke checks, professor/reviewer reproduction, and future benchmark
#   harness validation.
#
# Permission model:
#   The image creates/uses an `ubuntu` user and switches to that user after
#   dependency installation. The Makefile Docker targets also pass the host
#   UID/GID at `docker run` time. This double layer prevents root-owned build
#   artifacts when the repository is bind-mounted from WSL2 or Linux.
#
# Important:
#   Final publication benchmarks should be run on a stable documented host
#   or clean VM, not assumed from a developer laptop container alone.

FROM ubuntu:24.04

ARG X64LENS_CANDIDATE_TREE
ARG X64LENS_CONTEXT_AUTHORITY_SHA256
ARG X64LENS_SOURCE_MANIFEST_SHA256
LABEL org.x64lens.candidate-tree=$X64LENS_CANDIDATE_TREE \
      org.x64lens.context-authority-sha256=$X64LENS_CONTEXT_AUTHORITY_SHA256 \
      org.x64lens.source-manifest-sha256=$X64LENS_SOURCE_MANIFEST_SHA256
ENV X64LENS_CANDIDATE_TREE=$X64LENS_CANDIDATE_TREE
ENV DEBIAN_FRONTEND=noninteractive

# Install the baseline tools needed for local build/test parity. GCC and
# Clang are both development-only inputs for the provisional corpus matrix;
# they do not become runtime dependencies of the freestanding analyzer.
# Optional comparison tools such as ROPgadget, Ropper, and ropr remain
# intentionally outside the image because publication baseline environments
# should record tool installation and versions explicitly.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       binutils \
       ca-certificates \
       curl \
       gdb \
       git \
       gcc \
       clang \
       make \
       nasm \
       python3 \
       python3-jsonschema \
       time \
       unzip \
       zip \
    && rm -rf /var/lib/apt/lists/*

# Ubuntu 24.04 images commonly provide an `ubuntu` user. This fallback keeps
# the Dockerfile robust if that ever changes in a derivative image.
RUN if ! id -u ubuntu >/dev/null 2>&1; then useradd -m -s /bin/bash -u 1000 ubuntu; fi

# The Dockerfile is executed only through the exact context generated by
# tools/gitless-source-manifest.py.  source/ contains the authenticated staged
# Git tree and nothing else; the manifest is kept outside /work so image-owned
# validation can prove exact recursive source membership after Git metadata is
# deliberately removed.
WORKDIR /work
COPY source/ /work/
COPY source-manifest.json /x64lens-source-manifest.json

ENV X64LENS_SOURCE_MANIFEST=/x64lens-source-manifest.json
ENV X64LENS_SOURCE_AUTHORITY_ROOT=/work
ENV PYTHONDONTWRITEBYTECODE=1

# Validate exact Git-less source custody and repository shape at image build
# time.  The full binary build remains an explicit make target so build errors
# are visible rather than hidden in an opaque image layer.
RUN python3 /work/tools/gitless-source-manifest.py verify \
        --root /work --manifest /x64lens-source-manifest.json \
    && make scaffold-check \
    && chmod 0444 /x64lens-source-manifest.json

USER ubuntu
ENV HOME=/home/ubuntu
ENV X64LENS_RUN_ROOT=${HOME}/x64lens-run

CMD ["bash"]
