; patterns.asm
;
; Purpose:
;   Exact opcode-template matcher for raw gadget candidates.
;
; Module scope:
;   Consume raw candidate records produced by scanner.asm and tag candidates
;   with known x86_64 byte-template pattern IDs plus bounded structural facts.
;   This module does not assign semantic classes, scores, decoder validity, or
;   exploitability interpretation. Those responsibilities remain downstream.
;
; Sprint 10 scope:
;   Patch 046 adds one conservative two-pop argument-control family. Patch 047
;   adds one exact register-direct `mov r64, r64; ret` family for opcode 89/8b
;   with REX.W and ModRM.mod=3. Patch 048 adds a bounded positive aligned
;   `add rsp, imm8; ret` family. Ordered pattern register IDs remain in the
;   reserved gadget_record tail, so record size, arena size, and capacity do not
;   grow. Unsupported, duplicate, stack-pointer, memory, or 32-bit forms fall
;   back to the strongest previously supported suffix ending at the same return.
;
; Safety model:
;   Candidate byte ranges are generated by scanner.asm after executable-region
;   bounds checks. Every backward read remains inside the retained candidate
;   window. Matching is exact byte recognition, not full instruction decoding.

bits 64
default rel

%include "errors.inc"
%include "structs.inc"

%macro SET_PATTERN 1
    mov     dword [r15 + GADGET_PATTERN_ID], %1
    inc     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT]
    jmp     .next_candidate
%endmacro

; Decode one immediately preceding pop r64 instruction.
;
; Parameters:
;   1 = exclusive end offset
;   2 = candidate window start offset
;   3 = output instruction start register (64-bit)
;   4 = output register-ID register (32-bit)
;   5 = failure label
;
; Clobbers RAX, RDX. The mapped target base is held in R14.
%macro DECODE_POP_BACKWARD 5
    mov     %3, %1
    cmp     %3, %2
    jbe     %5
    dec     %3

    movzx   eax, byte [r14 + %3]
    cmp     eax, 0x58
    jb      %5
    cmp     eax, 0x5f
    ja      %5

    ; A preceding 0x41 is the REX.B prefix for pop r8-r15. It is consumed only
    ; when it remains inside the retained candidate window.
    cmp     %3, %2
    jbe     %%legacy
    cmp     byte [r14 + %3 - 1], 0x41
    jne     %%legacy
    dec     %3
    sub     eax, 0x58
    add     eax, REG_R8_BIT
    mov     %4, eax
    jmp     %%done

%%legacy:
    sub     eax, 0x58
    lea     rdx, [rel legacy_pop_reg_ids]
    movzx   %4, byte [rdx + rax]
%%done:
%endmacro

section .rodata
; Opcode order 58-5f is rax, rcx, rdx, rbx, rsp, rbp, rsi, rdi. Store the
; canonical register IDs used by register bitmaps and ordered pattern metadata.
legacy_pop_reg_ids:
    db REG_RAX_BIT, REG_RCX_BIT, REG_RDX_BIT, REG_RBX_BIT
    db REG_RSP_BIT, REG_RBP_BIT, REG_RSI_BIT, REG_RDI_BIT

; PATTERN_* ID for each canonical register ID 0-15.
single_pop_pattern_ids:
    db PATTERN_POP_RAX_RET, PATTERN_POP_RBX_RET
    db PATTERN_POP_RCX_RET, PATTERN_POP_RDX_RET
    db PATTERN_POP_RSI_RET, PATTERN_POP_RDI_RET
    db PATTERN_POP_RBP_RET, PATTERN_POP_RSP_RET
    db PATTERN_POP_R8_RET, PATTERN_POP_R9_RET
    db PATTERN_POP_R10_RET, PATTERN_POP_R11_RET
    db PATTERN_POP_R12_RET, PATTERN_POP_R13_RET
    db PATTERN_POP_R14_RET, PATTERN_POP_R15_RET

section .text
global x64lens_patterns_match_exact

; x64lens_patterns_match_exact(mapped_base=rdi, gadget_summary=rsi,
;                              gadget_records=rdx) -> rax=status
;
; Inputs:
;   RDI = mapped target file base
;   RSI = gadget_summary record
;   RDX = gadget_record[] buffer
;
; Output:
;   RAX = EXIT_OK on success
;
; Clobbers:
;   Caller-saved registers plus GADGET_PATTERN_ID,
;   GADGET_PATTERN_REG_COUNT, GADGET_PATTERN_REG_ORDER, and
;   GADGET_SUMMARY_PATTERN_COUNT.
x64lens_patterns_match_exact:
    push    rbp
    push    rbx
    push    r12
    push    r13
    push    r14
    push    r15

    mov     r14, rdi            ; mapped file base
    mov     r13, rsi            ; gadget_summary pointer
    mov     r12, rdx            ; gadget_record[] pointer

    mov     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT], 0
    xor     rbp, rbp            ; candidate index

.candidate_loop:
    cmp     rbp, [r13 + GADGET_SUMMARY_COUNT]
    jae     .ok

    mov     rax, rbp
    imul    rax, rax, GADGET_RECORD_SIZE
    lea     r15, [r12 + rax]

    mov     dword [r15 + GADGET_PATTERN_ID], PATTERN_UNKNOWN
    mov     qword [r15 + GADGET_PATTERN_REG_COUNT], 0

    mov     eax, [r15 + GADGET_TERMINATOR_TYPE]
    cmp     eax, GADGET_TERM_RET
    je      .match_ret_terminated
    cmp     eax, GADGET_TERM_RET_IMM16
    je      .match_ret_imm16
    jmp     .next_candidate

.match_ret_imm16:
    SET_PATTERN PATTERN_RET_IMM16

.match_ret_terminated:
    ; RSI = terminator file offset; RBX = candidate window start.
    mov     rsi, [r15 + GADGET_FILE_OFFSET]
    mov     rbx, [r15 + GADGET_BYTE_START]
    cmp     rsi, rbx
    jb      .next_candidate

    ; syscall; ret = 0f 05 c3. Check before register-bearing families.
    mov     rax, rsi
    sub     rax, rbx
    cmp     rax, 2
    jb      .check_stack_adjust
    cmp     byte [r14 + rsi - 2], 0x0f
    jne     .check_stack_adjust
    cmp     byte [r14 + rsi - 1], 0x05
    jne     .check_stack_adjust
    SET_PATTERN PATTERN_SYSCALL_RET

.check_stack_adjust:
    ; Exact supported form: 48 83 c4 imm8 c3 (add rsp, imm8; ret).
    ; The sign-extended immediate must be positive, nonzero, and divisible
    ; by eight. Negative, no-op, and byte-granular adjustments remain bare-ret
    ; fallbacks rather than receiving alignment semantics.
    mov     rax, rsi
    sub     rax, rbx
    cmp     rax, 4
    jb      .check_reg_transfer
    cmp     byte [r14 + rsi - 4], 0x48
    jne     .check_reg_transfer
    cmp     byte [r14 + rsi - 3], 0x83
    jne     .check_reg_transfer
    cmp     byte [r14 + rsi - 2], 0xc4
    jne     .check_reg_transfer
    movzx   eax, byte [r14 + rsi - 1]
    test    eax, eax
    jz      .check_reg_transfer
    test    eax, 0x80
    jnz     .check_reg_transfer
    test    eax, 0x07
    jnz     .check_reg_transfer
    SET_PATTERN PATTERN_ADD_RSP_IMM8_RET

.check_reg_transfer:
    ; Exact supported form:
    ;   REX.W + (89 /r | 8b /r) + ModRM.mod=3 + ret
    ;
    ; PATTERN_REG_ORDER stores destination in the low nibble and source in the
    ; next nibble. RSP participation and no-op self moves are intentionally
    ; excluded so this family has a bounded stack effect and a meaningful write.
    mov     rax, rsi
    sub     rax, rbx
    cmp     rax, 3
    jb      .check_multi_pop

    movzx   r8d, byte [r14 + rsi - 3]    ; REX prefix
    mov     eax, r8d
    and     eax, 0xf8
    cmp     eax, 0x48                    ; REX.W, optional R/X/B bits
    jne     .check_multi_pop

    movzx   r9d, byte [r14 + rsi - 2]    ; mov opcode
    cmp     r9d, 0x89
    je      .reg_transfer_opcode_ok
    cmp     r9d, 0x8b
    jne     .check_multi_pop
.reg_transfer_opcode_ok:

    movzx   r10d, byte [r14 + rsi - 1]   ; ModRM
    mov     eax, r10d
    and     eax, 0xc0
    cmp     eax, 0xc0                    ; register-direct only
    jne     .check_multi_pop

    mov     r11d, r10d
    and     r11d, 0x07                   ; r/m field
    test    r8d, 0x01                    ; REX.B extends r/m
    jz      .reg_transfer_rm_ready
    add     r11d, 8
.reg_transfer_rm_ready:
    cmp     r11d, 8
    jae     .reg_transfer_rm_canonical
    lea     rdx, [rel legacy_pop_reg_ids]
    movzx   r11d, byte [rdx + r11]
.reg_transfer_rm_canonical:

    mov     ecx, r10d
    shr     ecx, 3
    and     ecx, 0x07                    ; reg field
    test    r8d, 0x04                    ; REX.R extends reg
    jz      .reg_transfer_reg_ready
    add     ecx, 8
.reg_transfer_reg_ready:
    cmp     ecx, 8
    jae     .reg_transfer_reg_canonical
    lea     rdx, [rel legacy_pop_reg_ids]
    movzx   ecx, byte [rdx + rcx]
.reg_transfer_reg_canonical:

    cmp     r9d, 0x89
    jne     .reg_transfer_opcode_8b
    mov     edx, r11d                    ; 89 /r: destination = r/m
    mov     eax, ecx                     ;         source = reg
    jmp     .reg_transfer_roles_ready
.reg_transfer_opcode_8b:
    mov     edx, ecx                     ; 8b /r: destination = reg
    mov     eax, r11d                    ;         source = r/m
.reg_transfer_roles_ready:

    cmp     edx, eax
    je      .check_multi_pop
    cmp     edx, REG_RSP_BIT
    je      .check_multi_pop
    cmp     eax, REG_RSP_BIT
    je      .check_multi_pop

    mov     ecx, eax
    shl     ecx, 4
    or      ecx, edx
    mov     dword [r15 + GADGET_PATTERN_REG_COUNT], 2
    mov     dword [r15 + GADGET_PATTERN_REG_ORDER], ecx
    SET_PATTERN PATTERN_MOV_REG_REG_RET

.check_multi_pop:
    ; Decode the pop immediately before ret, then the pop immediately before it.
    ; R8/R9 hold the second instruction; R10/R11 hold the first instruction.
    DECODE_POP_BACKWARD rsi, rbx, r8, r9d, .check_single_pop
    DECODE_POP_BACKWARD r8, rbx, r10, r11d, .check_single_pop

    mov     edx, ARG_CONTROL_REG_MASK
    bt      edx, r9d
    jnc     .check_single_pop
    bt      edx, r11d
    jnc     .check_single_pop
    cmp     r9d, r11d
    je      .check_single_pop

    ; Least-significant nibble is execution order entry zero.
    mov     eax, r9d
    shl     eax, 4
    or      eax, r11d
    mov     dword [r15 + GADGET_PATTERN_REG_COUNT], 2
    mov     dword [r15 + GADGET_PATTERN_REG_ORDER], eax
    SET_PATTERN PATTERN_MULTI_POP_RET

.check_single_pop:
    DECODE_POP_BACKWARD rsi, rbx, r8, r9d, .check_leave
    cmp     r9d, REG_R15_BIT
    ja      .check_leave

    mov     dword [r15 + GADGET_PATTERN_REG_COUNT], 1
    mov     dword [r15 + GADGET_PATTERN_REG_ORDER], r9d
    lea     rdx, [rel single_pop_pattern_ids]
    movzx   eax, byte [rdx + r9]
    mov     dword [r15 + GADGET_PATTERN_ID], eax
    inc     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT]
    jmp     .next_candidate

.check_leave:
    cmp     rsi, rbx
    jbe     .bare_ret
    cmp     byte [r14 + rsi - 1], 0xc9
    je      .leave_ret

.bare_ret:
    SET_PATTERN PATTERN_RET

.leave_ret:
    SET_PATTERN PATTERN_LEAVE_RET

.next_candidate:
    inc     rbp
    jmp     .candidate_loop

.ok:
    xor     eax, eax
    pop     r15
    pop     r14
    pop     r13
    pop     r12
    pop     rbx
    pop     rbp
    ret
