; patterns.asm
;
; Purpose:
;   Exact opcode-template matcher for raw gadget candidates.
;
; Module scope:
;   Consume raw candidate records produced by scanner.asm and tag candidates
;   with known x86_64 byte-template pattern IDs plus bounded structural facts.
;   This module does not assign semantic classes, scores, decoder validity, or
;   exploitability interpretation. Those responsibilities remain downstream.
;
; Sprint 10 Patch 046 scope:
;   Preserve the existing single-suffix catalog and add one conservative
;   two-pop argument-control family. Ordered pop-register IDs are stored in the
;   reserved tail of gadget_record without increasing record or arena size.
;   Multi-pop promotion is limited to two distinct System V argument registers;
;   unsupported or duplicate pairs fall back to the strongest existing
;   single-pop suffix ending at the same return.
;
; Safety model:
;   Candidate byte ranges are generated by scanner.asm after executable-region
;   bounds checks. Every backward read remains inside the retained candidate
;   window. Matching is exact byte recognition, not full instruction decoding.

bits 64
default rel

%include "errors.inc"
%include "structs.inc"

%macro SET_PATTERN 1
    mov     dword [r15 + GADGET_PATTERN_ID], %1
    inc     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT]
    jmp     .next_candidate
%endmacro

; Decode one immediately preceding pop r64 instruction.
;
; Parameters:
;   1 = exclusive end offset
;   2 = candidate window start offset
;   3 = output instruction start register (64-bit)
;   4 = output register-ID register (32-bit)
;   5 = failure label
;
; Clobbers RAX, RDX. The mapped target base is held in R14.
%macro DECODE_POP_BACKWARD 5
    mov     %3, %1
    cmp     %3, %2
    jbe     %5
    dec     %3

    movzx   eax, byte [r14 + %3]
    cmp     eax, 0x58
    jb      %5
    cmp     eax, 0x5f
    ja      %5

    ; A preceding 0x41 is the REX.B prefix for pop r8-r15. It is consumed only
    ; when it remains inside the retained candidate window.
    cmp     %3, %2
    jbe     %%legacy
    cmp     byte [r14 + %3 - 1], 0x41
    jne     %%legacy
    dec     %3
    sub     eax, 0x58
    add     eax, REG_R8_BIT
    mov     %4, eax
    jmp     %%done

%%legacy:
    sub     eax, 0x58
    lea     rdx, [rel legacy_pop_reg_ids]
    movzx   %4, byte [rdx + rax]
%%done:
%endmacro

section .rodata
; Opcode order 58-5f is rax, rcx, rdx, rbx, rsp, rbp, rsi, rdi. Store the
; canonical register IDs used by register bitmaps and ordered pattern metadata.
legacy_pop_reg_ids:
    db REG_RAX_BIT, REG_RCX_BIT, REG_RDX_BIT, REG_RBX_BIT
    db REG_RSP_BIT, REG_RBP_BIT, REG_RSI_BIT, REG_RDI_BIT

; PATTERN_* ID for each canonical register ID 0-15.
single_pop_pattern_ids:
    db PATTERN_POP_RAX_RET, PATTERN_POP_RBX_RET
    db PATTERN_POP_RCX_RET, PATTERN_POP_RDX_RET
    db PATTERN_POP_RSI_RET, PATTERN_POP_RDI_RET
    db PATTERN_POP_RBP_RET, PATTERN_POP_RSP_RET
    db PATTERN_POP_R8_RET, PATTERN_POP_R9_RET
    db PATTERN_POP_R10_RET, PATTERN_POP_R11_RET
    db PATTERN_POP_R12_RET, PATTERN_POP_R13_RET
    db PATTERN_POP_R14_RET, PATTERN_POP_R15_RET

section .text
global x64lens_patterns_match_exact

; x64lens_patterns_match_exact(mapped_base=rdi, gadget_summary=rsi,
;                              gadget_records=rdx) -> rax=status
;
; Inputs:
;   RDI = mapped target file base
;   RSI = gadget_summary record
;   RDX = gadget_record[] buffer
;
; Output:
;   RAX = EXIT_OK on success
;
; Clobbers:
;   Caller-saved registers plus GADGET_PATTERN_ID,
;   GADGET_PATTERN_REG_COUNT, GADGET_PATTERN_REG_ORDER, and
;   GADGET_SUMMARY_PATTERN_COUNT.
x64lens_patterns_match_exact:
    push    rbp
    push    rbx
    push    r12
    push    r13
    push    r14
    push    r15

    mov     r14, rdi            ; mapped file base
    mov     r13, rsi            ; gadget_summary pointer
    mov     r12, rdx            ; gadget_record[] pointer

    mov     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT], 0
    xor     rbp, rbp            ; candidate index

.candidate_loop:
    cmp     rbp, [r13 + GADGET_SUMMARY_COUNT]
    jae     .ok

    mov     rax, rbp
    imul    rax, rax, GADGET_RECORD_SIZE
    lea     r15, [r12 + rax]

    mov     dword [r15 + GADGET_PATTERN_ID], PATTERN_UNKNOWN
    mov     qword [r15 + GADGET_PATTERN_REG_COUNT], 0

    mov     eax, [r15 + GADGET_TERMINATOR_TYPE]
    cmp     eax, GADGET_TERM_RET
    je      .match_ret_terminated
    cmp     eax, GADGET_TERM_RET_IMM16
    je      .match_ret_imm16
    jmp     .next_candidate

.match_ret_imm16:
    SET_PATTERN PATTERN_RET_IMM16

.match_ret_terminated:
    ; RSI = terminator file offset; RBX = candidate window start.
    mov     rsi, [r15 + GADGET_FILE_OFFSET]
    mov     rbx, [r15 + GADGET_BYTE_START]
    cmp     rsi, rbx
    jb      .next_candidate

    ; syscall; ret = 0f 05 c3. Check before pop-family recognition.
    mov     rax, rsi
    sub     rax, rbx
    cmp     rax, 2
    jb      .check_multi_pop
    cmp     byte [r14 + rsi - 2], 0x0f
    jne     .check_multi_pop
    cmp     byte [r14 + rsi - 1], 0x05
    jne     .check_multi_pop
    SET_PATTERN PATTERN_SYSCALL_RET

.check_multi_pop:
    ; Decode the pop immediately before ret, then the pop immediately before it.
    ; R8/R9 hold the second instruction; R10/R11 hold the first instruction.
    DECODE_POP_BACKWARD rsi, rbx, r8, r9d, .check_single_pop
    DECODE_POP_BACKWARD r8, rbx, r10, r11d, .check_single_pop

    mov     edx, ARG_CONTROL_REG_MASK
    bt      edx, r9d
    jnc     .check_single_pop
    bt      edx, r11d
    jnc     .check_single_pop
    cmp     r9d, r11d
    je      .check_single_pop

    ; Least-significant nibble is execution order entry zero.
    mov     eax, r9d
    shl     eax, 4
    or      eax, r11d
    mov     dword [r15 + GADGET_PATTERN_REG_COUNT], 2
    mov     dword [r15 + GADGET_PATTERN_REG_ORDER], eax
    SET_PATTERN PATTERN_MULTI_POP_RET

.check_single_pop:
    DECODE_POP_BACKWARD rsi, rbx, r8, r9d, .check_leave
    cmp     r9d, REG_R15_BIT
    ja      .check_leave

    mov     dword [r15 + GADGET_PATTERN_REG_COUNT], 1
    mov     dword [r15 + GADGET_PATTERN_REG_ORDER], r9d
    lea     rdx, [rel single_pop_pattern_ids]
    movzx   eax, byte [rdx + r9]
    mov     dword [r15 + GADGET_PATTERN_ID], eax
    inc     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT]
    jmp     .next_candidate

.check_leave:
    cmp     rsi, rbx
    jbe     .bare_ret
    cmp     byte [r14 + rsi - 1], 0xc9
    je      .leave_ret

.bare_ret:
    SET_PATTERN PATTERN_RET

.leave_ret:
    SET_PATTERN PATTERN_LEAVE_RET

.next_candidate:
    inc     rbp
    jmp     .candidate_loop

.ok:
    xor     eax, eax
    pop     r15
    pop     r14
    pop     r13
    pop     r12
    pop     rbx
    pop     rbp
    ret
