; patterns.asm
;
; Purpose:
;   Exact opcode-template matcher for raw gadget candidates.
;
; Module scope:
;   Consume raw candidate records produced by scanner.asm and tag candidates
;   with known x86_64 byte-template pattern IDs. This module intentionally
;   does not assign semantic classes, register-control bitmaps, scores, or
;   exploitability interpretation. Those responsibilities belong to
;   classifier.asm and scoring.asm in later sprints.
;
; Sprint 3 Phase D scope:
;   Recognize small exact templates that are already present in the controlled
;   tests/bin/gadgets fixture: pop-reg-ret, leave-ret, syscall-ret, ret, and
;   ret imm16. Matching is byte-template based, not full instruction decoding.
;
; Safety model:
;   Candidate byte ranges are generated by scanner.asm after executable-region
;   bounds checks. This module still refuses to read before each candidate
;   window start when looking backward from a return terminator.

bits 64
default rel

%include "errors.inc"
%include "structs.inc"

%macro SET_PATTERN 1
    mov     dword [r15 + GADGET_PATTERN_ID], %1
    inc     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT]
    jmp     .next_candidate
%endmacro

section .text
global x64lens_patterns_match_exact

; x64lens_patterns_match_exact(mapped_base=rdi, gadget_summary=rsi, gadget_records=rdx)
;     -> rax=status
;
; Inputs:
;   RDI = mapped target file base
;   RSI = gadget_summary record
;   RDX = gadget_record[] buffer
;
; Output:
;   RAX = EXIT_OK on success
;
; Clobbers:
;   Caller-saved registers plus GADGET_PATTERN_ID fields and
;   GADGET_SUMMARY_PATTERN_COUNT.
x64lens_patterns_match_exact:
    push    rbp
    push    rbx
    push    r12
    push    r13
    push    r14
    push    r15

    mov     r14, rdi            ; mapped file base
    mov     r13, rsi            ; gadget_summary pointer
    mov     r12, rdx            ; gadget_record[] pointer

    mov     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT], 0
    xor     rbp, rbp            ; candidate index

.candidate_loop:
    cmp     rbp, [r13 + GADGET_SUMMARY_COUNT]
    jae     .ok

    mov     rax, rbp
    imul    rax, rax, GADGET_RECORD_SIZE
    lea     r15, [r12 + rax]    ; current gadget_record pointer

    mov     dword [r15 + GADGET_PATTERN_ID], PATTERN_UNKNOWN

    mov     eax, [r15 + GADGET_TERMINATOR_TYPE]
    cmp     eax, GADGET_TERM_RET
    je      .match_ret_terminated
    cmp     eax, GADGET_TERM_RET_IMM16
    je      .match_ret_imm16
    jmp     .next_candidate

.match_ret_imm16:
    ; `ret imm16` was already bounds-checked as a three-byte terminator by the
    ; raw scanner. Record the exact template, but do not infer semantics yet.
    SET_PATTERN PATTERN_RET_IMM16

.match_ret_terminated:
    ; RAX = terminator file offset. RBX = candidate byte-window start.
    ; RDX = number of candidate bytes before the one-byte ret terminator.
    mov     rax, [r15 + GADGET_FILE_OFFSET]
    mov     rbx, [r15 + GADGET_BYTE_START]
    cmp     rax, rbx
    jb      .next_candidate
    mov     rdx, rax
    sub     rdx, rbx

    ; Highest-specificity patterns first.
    ; syscall; ret = 0f 05 c3
    cmp     rdx, 2
    jb      .check_one_byte_prefixes
    cmp     byte [r14 + rax - 2], 0x0f
    jne     .check_rex_pop
    cmp     byte [r14 + rax - 1], 0x05
    jne     .check_rex_pop
    SET_PATTERN PATTERN_SYSCALL_RET

.check_rex_pop:
    ; pop r8-r15; ret = 41 58-5f c3
    cmp     byte [r14 + rax - 2], 0x41
    jne     .check_one_byte_prefixes
    movzx   ecx, byte [r14 + rax - 1]
    cmp     ecx, 0x58
    jb      .check_one_byte_prefixes
    cmp     ecx, 0x5f
    ja      .check_one_byte_prefixes
    sub     ecx, 0x58
    add     ecx, PATTERN_POP_R8_RET
    mov     dword [r15 + GADGET_PATTERN_ID], ecx
    inc     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT]
    jmp     .next_candidate

.check_one_byte_prefixes:
    ; leave; ret = c9 c3
    ; pop r64; ret = 58-5f c3
    cmp     rdx, 1
    jb      .bare_ret

    movzx   ecx, byte [r14 + rax - 1]
    cmp     ecx, 0xc9
    je      .leave_ret

    cmp     ecx, 0x58
    jb      .bare_ret
    cmp     ecx, 0x5f
    ja      .bare_ret

    ; x86_64 pop encoding order for opcodes 58-5f is:
    ; rax, rcx, rdx, rbx, rsp, rbp, rsi, rdi.
    sub     ecx, 0x58
    add     ecx, PATTERN_POP_RAX_RET
    mov     dword [r15 + GADGET_PATTERN_ID], ecx
    inc     qword [r13 + GADGET_SUMMARY_PATTERN_COUNT]
    jmp     .next_candidate

.leave_ret:
    SET_PATTERN PATTERN_LEAVE_RET

.bare_ret:
    ; A raw one-byte ret remains useful as an alignment candidate later, but
    ; Sprint 3 only records the exact byte-template ID. Semantic assignment is
    ; intentionally deferred to classifier.asm.
    SET_PATTERN PATTERN_RET

.next_candidate:
    inc     rbp
    jmp     .candidate_loop

.ok:
    xor     rax, rax
    pop     r15
    pop     r14
    pop     r13
    pop     r12
    pop     rbx
    pop     rbp
    ret
