; dynamic-metadata-layout-authority.asm
;
; Purpose:
;   Export the private dynamic-metadata side-car ABI directly from NASM's
;   include/structs.inc authority. The descriptor is development-only and is
;   never linked into the freestanding x64lens runtime.
;
; Roadmap role:
;   Patch 075 froze the private DT_TEXTREL/DF_TEXTREL prefix. Patch 076 extends
;   the descriptor with distinct bounded DT_RPATH and DT_RUNPATH records and
;   exact-value storage. Future families must extend it deliberately.

bits 64
default rel

%include "structs.inc"

%define DYNAMIC_METADATA_LAYOUT_MAGIC       0x58363444594e4d44
%define DYNAMIC_METADATA_LAYOUT_VERSION     2
%define DYNAMIC_METADATA_LAYOUT_FIELD_COUNT 44

section .rodata align=8
global x64lens_dynamic_metadata_layout_descriptor
global x64lens_dynamic_metadata_layout_descriptor_size

x64lens_dynamic_metadata_layout_descriptor:
    dq DYNAMIC_METADATA_LAYOUT_MAGIC
    dq DYNAMIC_METADATA_LAYOUT_VERSION
    dq DYNAMIC_METADATA_LAYOUT_FIELD_COUNT

    dq DYNAMIC_METADATA_CTX_CARRIER_COUNT
    dq DYNAMIC_METADATA_CTX_TEXTREL_TAG_COUNT
    dq DYNAMIC_METADATA_CTX_FLAGS_COUNT
    dq DYNAMIC_METADATA_CTX_FLAGS_FIRST_VALUE
    dq DYNAMIC_METADATA_CTX_FLAGS_AND
    dq DYNAMIC_METADATA_CTX_FLAGS_OR
    dq DYNAMIC_METADATA_CTX_FULL_VALUE_CONFLICTS
    dq DYNAMIC_METADATA_CTX_TEXTREL_CONFLICTS
    dq DYNAMIC_METADATA_CTX_TABLE_COMPLETE
    dq DYNAMIC_METADATA_CTX_TEXTREL_STATE

    dq DYNAMIC_METADATA_CARRIER_TAG
    dq DYNAMIC_METADATA_CARRIER_INDEX
    dq DYNAMIC_METADATA_CARRIER_FILE_OFFSET
    dq DYNAMIC_METADATA_CARRIER_VALUE
    dq DYNAMIC_METADATA_CARRIER_RECORD_SIZE
    dq DYNAMIC_METADATA_CARRIER_MAX
    dq DYNAMIC_METADATA_CONTEXT_V1_SIZE

    dq DYNAMIC_METADATA_CTX_SEARCH_RECORD_COUNT
    dq DYNAMIC_METADATA_CTX_SEARCH_BYTES_USED
    dq DYNAMIC_METADATA_CTX_RPATH_CARRIER_COUNT
    dq DYNAMIC_METADATA_CTX_RUNPATH_CARRIER_COUNT
    dq DYNAMIC_METADATA_CTX_RPATH_VALUE_COUNT
    dq DYNAMIC_METADATA_CTX_RUNPATH_VALUE_COUNT
    dq DYNAMIC_METADATA_CTX_RPATH_VALUE_CONFLICTS
    dq DYNAMIC_METADATA_CTX_RUNPATH_VALUE_CONFLICTS
    dq DYNAMIC_METADATA_CTX_RPATH_FIRST_RECORD
    dq DYNAMIC_METADATA_CTX_RUNPATH_FIRST_RECORD
    dq DYNAMIC_METADATA_CTX_RPATH_STATE
    dq DYNAMIC_METADATA_CTX_RUNPATH_STATE
    dq DYNAMIC_METADATA_CTX_SEARCH_RECORDS

    dq DYNAMIC_METADATA_SEARCH_RECORD_TAG
    dq DYNAMIC_METADATA_SEARCH_RECORD_INDEX
    dq DYNAMIC_METADATA_SEARCH_RECORD_DYNAMIC_FILE_OFFSET
    dq DYNAMIC_METADATA_SEARCH_RECORD_STRING_TABLE_OFFSET
    dq DYNAMIC_METADATA_SEARCH_RECORD_STRING_FILE_OFFSET
    dq DYNAMIC_METADATA_SEARCH_RECORD_BYTE_POOL_OFFSET
    dq DYNAMIC_METADATA_SEARCH_RECORD_BYTE_LENGTH
    dq DYNAMIC_METADATA_SEARCH_RECORD_SIZE
    dq DYNAMIC_METADATA_SEARCH_RECORD_MAX
    dq DYNAMIC_METADATA_CTX_SEARCH_BYTES
    dq DYNAMIC_METADATA_SEARCH_BYTES_MAX

    dq DYNAMIC_METADATA_CONTEXT_SIZE
    dq PRIVATE_METADATA_DYNAMIC_OFFSET
    dq PRIVATE_METADATA_CONTEXT_SIZE
.end:

x64lens_dynamic_metadata_layout_descriptor_size:
    dq x64lens_dynamic_metadata_layout_descriptor.end - x64lens_dynamic_metadata_layout_descriptor

section .note.GNU-stack noalloc noexec nowrite progbits
